sudo: required
services:
    - docker

before_install:
    - docker build -t seejiahao/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true seejiahao/docker-react npm run test

language: generic

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react-aws"
    env: "DockerReactAws-env"
    bucket_name : "elasticbeanstalk-us-east-2-856375385484"
    bucket_path : "docker-react-aws"
    access_key_id : $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
        branch:master

    